apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: facebook
  name: facebook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: nginx
        name: nginx
