# microservices components 1 - main app 2 - external db
# 2 - external db
apiVersion: v1
kind: Service
metadata:
  name: weather-db
spec:
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: weather-db
---
apiVersion: apps/v1
kind: Deployment #StatefulSet
metadata:
  name: weather-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-db
  template:
    metadata:
      labels:
        app: weather-db
    spec:
      volumes:
      - hostPath:
          path: /weather_data
          type: ""
        name: data
      containers:
      - image: mariadb:10.3 #oracle/repliacation-rack-db:1.0.0
        name: mariadb
        ports:
        - containerPort: 3306
          name: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: weather
          - name: MYSQL_DATABASE
            value: weather
          - name: MYSQL_USER
            value: weather
          - name: MYSQL_PASSWORD
            value: weather
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
