apiVersion: v1
kind: Pod
metadata:
  labels:
    run: initc-syncup
  name: initc-syncup
spec:
  initContainers: 
  - command: 
    - curl
    - --output
    - /work-dir/index.html 
    - https://brainupgrade.in
    image: brainupgrade/tshoot
    name: box 
    volumeMounts: 
    - name: vol 
      mountPath: /work-dir 
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts: 
    - name: vol 
      mountPath: /usr/share/nginx/html 
  volumes: 
  - name: vol 
    emptyDir: {}