apiVersion: v1
kind: Pod
metadata:
  name: pending
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
      requests:
        cpu: "10"
        memory: "100Gi"
      limits:
        cpu: "10"
        memory: "100Gi"  
  