apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: payment
    tier: frontend
    release: ap-1
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
