apiVersion: v1
kind: Service
metadata:
  name: gamification-service
spec:
  type: ClusterIP
  selector:
    app: gamification-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377