apiVersion: v1
kind: Service
metadata:
  name: customer-db
  namespace: global-bank
spec:
  type: ClusterIP
  ports:
    - name: tcp
      port: 3306
      targetPort: 3306
  selector:
    app: customer-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db
  namespace: global-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
      - image: mariadb:10.3
        name: customer-db
        ports:
        - containerPort: 3306
          name: tcp
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: customer
          - name: MYSQL_DATABASE
            value: customer
          - name: MYSQL_USER
            value: customer
          - name: MYSQL_PASSWORD
            value: customer