apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      initContainers:
      - name: init-mydb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup account-db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting-for-database; sleep 2; done"]
      containers:
      - image: brainupgrade/global-bank-account:1.0.0
        name: account
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
          - name: java.security.egd
            value: file:/dev/./urandom
          - name: server.port
            value: "80"
          - name: spring.datasource.url
            value: jdbc:mariadb://account-db:3306/account
          - name: spring.datasource.driverClassName
            value: "org.mariadb.jdbc.Driver"
          - name: spring.jpa.database-platform
            value: "org.hibernate.dialect.MariaDBDialect"
          - name: spring.jpa.properties.hibernate.dialect
            value: "org.hibernate.dialect.MariaDBDialect"
          - name: spring.datasource.username
            value: "account"
          - name: spring.datasource.password
            value: "account"
          - name: feign.url-customer-service
            value: "customer/customer"
          - name: feign.url-auth-service
            value: "authentication/auth"
          - name: feign.url-transaction-service
            value: "transaction/transaction"
          - name: spring.jpa.hibernate.ddl-auto
            value: "create"  
          - name: spring.jpa.generate-ddl
            value: "true"    