FROM node:alpine

MAINTAINER "info@brainupgrade.in"

RUN apk update && apk add git 
RUN git clone https://github.com/harryhagrid/smart-bank-app.git && cd /smart-bank-app && git checkout develop

WORKDIR /smart-bank-app
RUN ["npm","install"]
CMD ["npm", "start"]

EXPOSE 5000
