apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins  
  ports:
  - port: 80
    name: "http"
    targetPort: 8080
  - port: 8080
    name: "ui"
    targetPort: 8080
  - port: 50000
    name: "slave"
    targetPort: 50000   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins    
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: init-chown
        image: alpine
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
        env:
        - name: JENKINS_HOME
          value: /var/jenkins_home
        - name: UID
          value: '1000'
        command:
        - sh
        - -c
        - if [ ! -f $JENKINS_HOME ]; then chown $UID:$UID -R $JENKINS_HOME; touch $JENKINS_HOME; chown $UID:$UID $JENKINS_HOME; fi
      containers:
        - name: jenkins
          image: brainupgrade/jenkins:2.274jdk11x
          securityContext:
            runAsUser: 0          
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=true -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "1024Mi"  
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-sock-volume
              mountPath: /var/run/docker.sock              
      volumes:
        - name: jenkins-home
          hostPath:
            path: /var/jenkins_home
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock              
            