FROM adoptopenjdk/maven-openjdk11  
WORKDIR /build
RUN apt-get update && apt-get install -y git 
RUN git clone https://github.com/brainupgrade-in/weather.git 
RUN cd /build/weather && mvn clean package
# docker build -t weather .
