apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - name: liveness
    image: brainupgrade/tshoot
    command:
    - /bin/sh
    args:
    - -c
    - while true; do touch /tmp/healthy;sleep 30; rm -rf /tmp/healthy;sleep 10;touch /tmp/healthy;done
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 5
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 1
# kubectl get events --sort-by='.metadata.creationTimestamp' -A
# k get events  --sort-by='.lastTimestamp'