apiVersion: v1
kind: Pod
metadata:
  name: probe-liveness-startup-http
spec:
  containers:
  - name: probe-liveness-startup-http
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 1
      successThreshold: 1
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      failureThreshold: 30
      successThreshold: 1
      periodSeconds: 10
      initialDelaySeconds: 9
