apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook
spec:
  replicas: 10
  selector:
    matchLabels:
      app: facebook
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: facebook
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: facebook-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
          limits:
            cpu: 4m
            memory: 4Mi
          requests:
            cpu: 4m
            memory: 4Mi  
