apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume-2
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /data-path-inside-container
      name: hostpath-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: hostpath-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate
