apiVersion: v1
kind: Pod
metadata:
  name: pod-local-storage
spec:
  volumes:
    - name: pvc-local-storage
      persistentVolumeClaim:
        claimName: pvc-local-storage
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/tmp"
          name: pvc-local-storage
      resources:
        limits:
          cpu: "20m"
          memory: "50Mi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi          