apiVersion: v1
kind: Pod
metadata:
  name: vol-emptydir
spec:
  containers:
  - image: nginx
    name: web-server
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

    