apiVersion: v1
kind: Pod
metadata:
  name: vol-emptydir
spec:
  containers:
  - image: nginx
    name: web-server
    resources: 
      limits:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}

    