apiVersion: v1
kind: Pod
metadata:
  name: vol-emptydir-sidecar
  labels:
    app: sidecar
spec:
  imagePullSecrets:
    - name: regcred
  volumes:
  - name: shared-storage
    emptyDir: {}
  containers:  
  - name: sidecar-container
    image: busybox 
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo -e '\n'$(date) >> /var/log/index.html; sleep 10;done"]
    resources:
      requests:
        cpu: "10m"
        memory: "25Mi"
      limits:
        cpu: "20m"
        memory: "50Mi"    
    volumeMounts:
    - name: shared-storage
      mountPath: /var/log
  - name: main-container
    image: nginx 
    resources:
      requests:
        cpu: "10m"
        memory: "25Mi"
      limits:
        cpu: "20m"
        memory: "50Mi"    
    volumeMounts:
    - name: shared-storage
      mountPath: /usr/share/nginx/html
