apiVersion: v1
kind: Pod
metadata:
  name: vol-hostpath
spec:
  # nodeName: ip-172-31-102-18.ec2.internal  (run 1)r1   r3
  # nodeName: ip-172-31-102-19.ec2.internal  (run 2) r2  r4
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /data-path-inside-container
      name: hostpath-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: hostpath-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate
