apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-local-storage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:  
      volumes:
        - name: pvc-local-storage
          persistentVolumeClaim:
            claimName: pvc-local-storage
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - mountPath: "/tmp"
              name: pvc-local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi          
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-node-affinity
spec:
  capacity:
    storage: 10Mi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - ap-south-1b      