apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebs-dynamic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebs-dynamic
  template:
    metadata:
      labels:
        app: ebs-dynamic
    spec:
      containers:
      - image: nginx
        name: test-container
        resources: 
          limits:
            memory: "64Mi"
            cpu: "250m"
        volumeMounts:
        - mountPath: /test-ebs
          name: ebs-volume
      volumes:
      - name: ebs-volume
        persistentVolumeClaim:
          claimName: ebs-dynamic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi