apiVersion: v1
kind: Pod
metadata:
  name: pod-ebs
spec:
  imagePullSecrets:
    - name: regcred
  nodeSelector:
    topology.kubernetes.io/zone: ap-south-1a
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
    - mountPath: /test-ebs
      name: ebs-volume
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"  
  volumes:
  - name: ebs-volume
    # This AWS EBS volume must already exist.
    awsElasticBlockStore:
      volumeID: vol-019fea9d477209e08
      fsType: ext4
      