apiVersion: v1
kind: Pod
metadata:
  name: config-volume
spec:
  containers:
    - name: test
      image: nginx
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
      resources:
        limits:
          cpu: "20m"
          memory: "50Mi"          
  volumes:
    - name: config-vol
      configMap:
        name: config-volume
        items:
          - key: log_level
            path: log.properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-volume
data:
  log_level: |
    debug=true
    sql=true
