kind: Pod
apiVersion: v1
metadata:
  name: test-efs-pod
spec:
  containers:
  - name: test-pod
    image: wordpress:5.3.2-apache
    volumeMounts:
      - name: efs-pvc
        mountPath: "/var/www/html"
  restartPolicy: "Never"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: efs-www-in
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-www-in
  labels:
    app: efs-www-in
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi    
  selector: 
    matchLabels: 
      app: efs-www-in
