apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-wordpress
  template:
    metadata:
      labels:
        app: efs-wordpress
    spec:
      containers:
      - name: test-pod
        image: wordpress:5.3.2-apache
        volumeMounts:
          - name: efs-pvc
            mountPath: "/var/www/html"
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs-www-in
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-www-in
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi    
