apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-joomla-site
spec:
  selector:
    matchLabels:
      app: joomla
  replicas: 1
  template:
    metadata:
      labels:
        app: joomla
    spec:
      securityContext:
        fsGroup: 1000    
      terminationGracePeriodSeconds: 10
      containers:
      - name: joomla
        image: joomla:4.3
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000        
          capabilities:
            add:
              - NET_BIND_SERVICE          
        env:
        - name: JOOMLA_DB_PASSWORD
          value: mtvlabeks
        - name: JOOMLA_DB_USER 
          value: mtvlabeks
        - name: JOOMLA_DB_NAME
          value: "joomla"
        - name: JOOMLA_DB_HOST
          value: "efs-joomla-mysql:3306"
        volumeMounts:
          - name: html
            mountPath: "/var/www/html"
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: joomla
---
apiVersion: v1
kind: Service
metadata:
  name: efs-joomla-site
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: joomla
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-joomla-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpasswd
        - name: MYSQL_PASSWORD
          value: mtvlabeks
        - name:  MYSQL_USER
          value: mtvlabeks
        - name: MYSQL_DATABASE
          value: joomla
        volumeMounts:
          - name: mysql
            mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: efs-joomla-mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: joomla
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi