apiVersion: apps/v1
kind: Deployment
metadata:
  name: txn-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: txn-collector
  template:
    metadata:
      labels:
        app: txn-collector
        region: ap-south-1
    spec:
      containers:
      - name: collector
        image: brainupgrade/nginx
        resources:
              requests:
                memory: "50Mi"
                cpu: "10m"
              limits:
                memory: "50Mi"
                cpu: "10m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detector
  template:
    metadata:
      labels:
        app: fraud-detector
        region: ap-south-1
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: txn-collector
                region: ap-south-1
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: detector
        image: brainupgrade/nginx
        resources:
              requests:
                memory: "50Mi"
                cpu: "10m"
              limits:
                memory: "50Mi"
                cpu: "10m"

        ports:
        - containerPort: 80
