apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: messaging
  template:
    metadata:
      labels:
        tier: messaging
    spec:
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: tier
                  operator: In  # NotIn, Exists, NotExists
                  values:
                  - messaging
              topologyKey: topology.kubernetes.io/zone
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                  matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - messaging
              topologyKey: kubernetes.io/hostname
        containers:
          - name: nginx
            image: nginx
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
