apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: cache
  template:
    metadata:
      labels:
        tier: cache
    spec:
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                  matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - front
              topologyKey: topology.kubernetes.io/zone
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:            
                labelSelector:
                  matchExpressions:
                  - key: tier
                    operator: In  # NotIn, Exists, NotExists
                    values:
                    - front
                topologyKey: kubernetes.io/hostname
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                  matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - cache
              topologyKey: kubernetes.io/hostname
        containers:
          - name: redis
            image: redis:3.2-alpine
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 80
