apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cache-store
spec:
  selector:
    matchLabels:
      app: cache-store
  replicas: 2
  template:
    metadata:
      labels:
        app: cache-store
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cache-store
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-server
        image: redis:3.2-alpine
