apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: facebook
  name: facebook
spec:
  replicas: 9
  selector:
    matchLabels:
      app: facebook
      release: v1
  template:
    metadata:
      labels:
        app: facebook
        release: v1
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello
        ports:
        - containerPort: 8080
          protocol: TCP