apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook
  template:
    metadata:
      labels:
        app: facebook
        
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: gcr.io/google-samples/hello-app:2.0
        name: hello
        ports:
        - containerPort: 8080
          protocol: TCP
