FROM ubuntu

LABEL MAINTAINER rajesh@brainupgrade.in

RUN apt-get update -y && apt-get install iputils-ping -y

ENTRYPOINT ["ping"]

CMD ["google.com"]

# docker build -f Dockerfile-ping -t myping .
# docker run myping 
# docker run myping yahoo.com
