apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v21
spec:
  selector:
    matchLabels:
      app: api-v2
  replicas: 1
  template:
    metadata:
      labels:
        app: api-v2
        release: canary
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In  #In, NotIn, Exists, DoesNotExist, Gt, Lt  
                values:
                - us-east-1c
      containers:
      - name: api-v2
        image: gcr.io/google-samples/hello-app:3.0
        ports:
        - containerPort: 8080