apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
spec:
  selector:
    matchLabels:
      app: api-v2
  replicas: 2
  template:
    metadata:
      labels:
        app: api-v2
    spec:
      containers:
      - name: api-v2
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080