apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1
spec:
  selector:
    matchLabels:
      app: api-v1
  replicas: 2
  template:
    metadata:
      labels:
        app: api-v1
    spec:
      containers:
      - name: api-v1
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080