apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: microk8s
  region: ap-southeast-1
  version: "1.21"
managedNodeGroups:
- name: managed-nodes
  labels:
    role: managed-nodes
  instanceType: t3a.small
  spot: true
  minSize: 1
  maxSize: 2
  desiredCapacity: 1
  volumeSize: 20
