apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-subpath-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: wordpress
        image: wordpress:5.3.2-apache
        volumeMounts:
          - name: html
            mountPath: "/var/www/html"
            subPath: html
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: wordpress-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-subpath-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpasswd"        
        - name: MYSQL_PASSWORD
          value: "passwd"        
        - name: MYSQL_USERNAME
          value: "admin"        
        - name: MYSQL_DATABASE
          value: "wordpress"        
        volumeMounts:
          - name: mysql
            mountPath: "/var/lib/mysql"
            subPath: mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: wordpress-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-simple
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      app: wordpress-mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress-mysql
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-simple
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-id
