apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-single-volume
spec:
  selector:
    matchLabels:
      app: efs-single-volume
  replicas: 1
  template:
    metadata:
      labels:
        app: efs-single-volume
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: tshoot
        image: brainupgrade/tshoot 
        volumeMounts:
        - name: efs-storage
          mountPath: /efs-data
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-simple
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-simple
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-id
