apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payroll
      region: india
  template:
    metadata:
      labels:
        app: payroll
        region: india
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In  #In, NotIn, Exists, DoesNotExist, Gt, Lt  
                values:
                - ap-south-1a
                - ap-south-1b
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kops.k8s.io/instancegroup
                operator: In  #NotIn,  DoesNotExist for AntiAffinity
                values:
                - spotnodes
      containers:
        - name: payroll
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
