FROM adoptopenjdk/maven-openjdk11  
WORKDIR /app
RUN apt-get update && apt-get install -y git 
RUN git clone https://github.com/brainupgrade-in/request-logger.git 
RUN cd /app/request-logger && mvn clean package
ENTRYPOINT ["java" ]
CMD ["-jar","/app/request-logger/target/app.jar"]
