apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-authdb
spec:
  podSelector:
    matchLabels:
      app: authdb
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: mtvlabeksa1
    ports:
    - protocol: TCP
      port: 3306
