kind: Namespace
apiVersion: v1
metadata:
  name: np-namespace
  annotations: 
    net.beta.kubernetes.io/network-policy: |
     {
       "ingress": {
          "isolation": "DefaultDeny"
        }
      }