apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-db-layer
spec:
  podSelector:
    matchLabels:
      app: weather-front
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/24  
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: klaas2112u1
      podSelector:
        matchLabels:
          app: weather-service    
    - podSelector:
        matchLabels:
          app: weather-service
    ports:
    - protocol: TCP
      port: 8080