apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-db-layer
spec:
  podSelector:
    matchLabels:
      app: paymentgw
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 140.90.0.0/16  # Partner network
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: location
      podSelector:
        matchLabels:
          app: commonlabel   
    - podSelector:
        matchLabels:
          app: fixedincome
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080      