apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-service-layer
spec:
  podSelector:
    matchLabels:
      app: reporting
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: apiservices
    ports:
    - protocol: TCP
      port: 80

# https://docs.tigera.io/calico/latest/getting-started/kubernetes/managed-public-cloud/eks
# https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy-configure.html