apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: np-service-layer
spec:
  podSelector:
    matchLabels:
      app: reporting
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: apiservices
    ports:
    - protocol: TCP
      port: 8080