FROM ubuntu
ENTRYPOINT ["top", "-b"]
CMD ["-c"]

# docker build -t epexec .
# docker run -itd --rm --name test  epexec 
# docker exec -it test ps aux
# Observation: CMD arguments are appended to EXEC arguments
