apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: migration-recurring-task
spec:
  schedule: "*/2 * * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: "Allow"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name:  regcred
          containers:
          - name: cron-job
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Migrating data to reporting server...;sleep 1;
          restartPolicy: OnFailure
