apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-pod-per-zone
spec:
  replicas: 10
  selector:
    matchLabels:
      app: one-pod-per-zone
  template:
    metadata:
      labels:
        app: one-pod-per-zone
    spec:
      topologySpreadConstraints:
      - maxSkew: 3
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: one-pod-per-zone
      containers:
      - image: brainupgrade/hello
        name: hello-app
