apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-front
spec:
  replicas: 10
  selector:
    matchLabels:
      app: weather
      tier: front
  template:
    metadata:
      labels:
        app: weather
        tier: front
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: weather
            tier: front
      containers:
      - image: brainupgrade/weather:openmeteo-v2
        name: weather
