apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-host
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-host
  template:
    metadata:
      labels:
        app: topology-host
    spec:
      nodeSelector:
        kubernetes.io/role: node
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: topology-host
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-app
