apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-services
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
      tier: apiservices
  template:
    metadata:
      labels:
        app: weather
        tier: apiservices
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: weather
            tier: apiservices
      containers:
      - image: brainupgrade/weather-services:openmeteo-v2
        name: weather-service
