apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticketing
      scope: internal
  template:
    metadata:
      labels:
        app: ticketing
        scope: internal
    spec:
      topologySpreadConstraints:
      - maxSkew: 3
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: ticketing
            scope: internal
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: ticketing
            scope: internal
      containers:
      - image: brainupgrade/hello
        name: ticketing-solution
