apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-live-streaming
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sports-live-streaming
  template:
    metadata:
      labels:
        app: sports-live-streaming
    spec:
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: sports-live-streaming
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/nodegroup
                operator: In
                values:
                - gpu-nodes
      containers:
      - name: streaming-server
        image: brainupgrade/hello
