apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-nodeaffinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-nodeaffinity
  template:
    metadata:
      labels:
        app: topology-nodeaffinity
    spec:
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: topology-nodeaffinity
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: NotIn
                values:
                - ap-south-1d
      containers:
      - name: hello
        image: brainupgrade/hello
