apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
spec:
  containers:
  - name: mypod
    image: redis
    resources:
      limits:
        cpu: "20m"
        memory: "50Mi"
    env:
      - name: spring.datasource.username
        valueFrom:
          secretKeyRef:
            name: db
            key: username
      - name: spring.datasource.password
        valueFrom:
          secretKeyRef:
            name: db
            key: password
      - name: spring.datasource.url
        valueFrom:
          secretKeyRef:
            name: db
            key: spring.datasource.url
    volumeMounts:
    - name: vol
      mountPath: "/etc/app"
      readOnly: true
  volumes:
  - name: vol
    secret:
      secretName: db
      items:
      - key: password
        path: credentials
