apiVersion: v1
kind: Pod
metadata:
  name: pod-preset-pod
  labels:
    app: website
    role: frontend
spec:
  containers:
    - name: website
      image: nginx
      ports:
        - containerPort: 80
# api server fix
# --extra-config=apiserver.runtime-config=settings.k8s.io/v1alpha1=true