apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logger-mysql
  labels:
    app: logger
spec:
  selector:
    matchLabels:
      app: logger
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: logger
        tier: mysql
    spec:
      containers:
      - image: mariadb
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: rootpassword
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: name
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: logger-pvc
