apiVersion: v1
kind: Service
metadata:
  name: logger-mysql
  labels:
    app: logger-mysql
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
  selector:
    app: logger
    tier: mysql