apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: mtls-productpage
spec:
  host: productpage
  subsets:
  - name: v1
    labels:
      version: v1  
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
