apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-node
spec:
  replicas: 1
  selector:
    matchLabels:
      component: schedule-node
  template:
    metadata:
      labels:
        component: schedule-node
    spec:
        nodeName: ip-192-168-113-151.ap-south-1.compute.internal
        containers:
          - name: test-app
            image: brainupgrade/hello:1.0
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 8080
            resources:
              requests:
                cpu: "100m"
                memory: "250Mi"  
