kind: PersistentVolume
apiVersion: v1
metadata:
  name: www
  labels:
    app: www
    volume-type: gp2
    aws-availability-zone: us-east-1a
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-0f75c0e5052f65cc6  # insert volume id
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain  