FROM openjdk:8-jre-alpine
COPY target/sba-services.jar /app.jar
ENTRYPOINT ["java"]
CMD ["-jar","/app.jar"]
EXPOSE 8080
# docker build -f Dockerfile-ms -t java-run .
# docker run -p 8080:8080 java-run