FROM openjdk:8-jre-alpine
MAINTAINER info@brainupgrade.in
COPY target/authentication.jar app.jar
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar","app.jar"]
# docker build -t java-run .
# docker run -p 8080:8080 java-run