# This file is used to deploy Prometheus for monitoring a Spring Boot application.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---  
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  serviceName: "prometheus"
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      serviceAccount: prometheus
      securityContext:
        fsGroup: 65534
      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 65534:65534 /prometheus"]
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus    
      containers:
      - name: prometheus
        image: prom/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - '--web.enable-admin-api'
          - "--web.enable-lifecycle" 
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus
        securityContext:
          runAsUser: 65534      
          runAsGroup: 65534                                
      - name: config-reloader
        image: jimmidyson/configmap-reload
        args:
        - --volume-dir=/etc/prometheus
        - --webhook-url=http://prometheus/-/reload
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus          
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 9090
  - name: prometheus
    port: 9090
    protocol: TCP
    targetPort: 9090
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: prometheus
  type: ClusterIP
