apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker
  name: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      volumes:
      - name: docker-home
        persistentVolumeClaim:
          claimName: docker-home
      containers:
      - image: brainupgrade/jenkins:dockeragent-v1
        name: docker
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 2048Mi
            cpu: 0.5
          requests:
            memory: 1024Mi
            cpu: 0.1
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ''
        volumeMounts:
          - name: docker-home
            mountPath: /var/lib/docker
---
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  type: ClusterIP
  selector:
    app: docker  
  ports:
  - port: 2375
    name: "docker"
    targetPort: 2375
  - port: 22
    name: "ssh"
    targetPort: 22
  - port: 80
    name: "http"
    targetPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: docker-home
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi