apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent-docker
  name: agent-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-docker
  template:
    metadata:
      labels:
        app: agent-docker
    spec:
      containers:
      - image: brainupgrade/jenkins:agent-docker
        name: agent-docker
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: DOCKER_HOST
          value: "tcp://docker:2375"
        - name: PASSWORD_ACCESS
          value: "true"
        - name: SUDO_ACCESS
          value: "true"  
        - name: USER_NAME
          value: ubuntu
        - name: USER_PASSWORD
          value: linux
---
apiVersion: v1
kind: Service
metadata:
  name: agent-docker
spec:
  type: ClusterIP
  selector:
    app: agent-docker  
  ports:
  - port: 22
    name: "tcp"
    targetPort: 2222
---
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  type: ClusterIP
  selector:
    app: docker  
  ports:
  - port: 2375
    name: "tcp"
    targetPort: 2375
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker
  name: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - image: brainupgrade/docker:20-dind
        name: docker
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ''    
