apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: ClusterIP
  selector:
    app: jenkins  
  ports:
  - port: 80
    name: "http"
    targetPort: 8080
  - port: 8080
    name: "ui"
    targetPort: 8080
  - port: 50000
    name: "slave"
    targetPort: 50000   
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /prometheus
    spec:
      initContainers:
      - name: init-chown
        image: alpine
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
        env:
        - name: JENKINS_HOME
          value: /var/jenkins_home
        - name: UID
          value: '1000'
        command:
        - sh
        - -c
        - if [ ! -f $JENKINS_HOME ]; then chown $UID:$UID -R $JENKINS_HOME; touch $JENKINS_HOME; chown $UID:$UID $JENKINS_HOME; fi        
      containers:
      - name: jenkins
        image: brainupgrade/jenkins:2.414.1x3
        imagePullPolicy: Always
        env:
        - name: DOCKER_HOST
          value: "tcp://docker:2375"
        - name: spring.application.name
          value: jenkins-mtvlabcicda1
        - name: management.metrics.tags.application
          value: jenkins-mtvlabcicda1
        resources:
          requests:
            cpu: 0.5
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 8080
          name: web
        - containerPort: 50000
          name: agent-port
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        startupProbe:
          httpGet:
            path: /static/jenkins/images/svgs/logo.svg
            port: 8080
          failureThreshold: 30
          successThreshold: 1
          periodSeconds: 10
          initialDelaySeconds: 30
        livenessProbe:
          httpGet:
            path: /static/jenkins/images/svgs/logo.svg
            port: 8080
          initialDelaySeconds: 60
          failureThreshold: 2
          successThreshold: 1
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /static/jenkins/images/svgs/logo.svg
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-home
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
spec:
  # storageClassName: efs-dynamic
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  resources:
    requests:
      storage: 5Gi