apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      volumes:
      - name: www-pv
        persistentVolumeClaim:
          claimName: www-pvc
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: topology.kubernetes.io/zone
      #           operator: In
      #           values:
      #           - us-east-1a
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #   - labelSelector:
        #       matchExpressions:
        #       - key: app
        #         operator: In
        #         values:
        #         - www
        #     topologyKey: "kubernetes.io/hostname"
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: nginx
        resources:
          limits:
            cpu: "20m"
            memory: "50Mi"          
        volumeMounts:
        - name: www-pv
          mountPath: /tmp