apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc
  labels:
    app: www
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels: 
      app: www
      volume-type: gp2
      aws-availability-zone: us-east-1a