apiVersion: v1
kind: Pod
metadata:
  name: tourist
spec:
  restartPolicy: Always
  containers:
  - name: web-app
    image: nginx:1.16-alpine
  # tolerations:
  #   - key: "visa/canada"
  #     operator: "Equal"
  #     value: "tourist"
  #     effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In  #In, NotIn, Exists, DoesNotExist, Gt, Lt  
            values:
            - us-east-1b
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: kops.k8s.io/instancegroup
            operator: In  #NotIn,  DoesNotExist for AntiAffinity
            values:
            - spotnodes
