kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclass-generic
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 
  zones: us-east-1b,us-east-1c
  iopsPerGB: "10" 
  fsType: ext4
