apiVersion: v1
kind: Pod
metadata:
  labels:
    app: image-analytics
    feature: aiml
  name: aiml
spec:
  nodeSelector:
    eks.amazonaws.com/nodegroup: gpu-nodes
  containers:
  - image: brainupgrade/hello
    name: image-analytics
  tolerations:
    - key: "storage"
      operator: "Equal"
      value: "ephemeral"
      effect: "NoSchedule"

# k taint node k8s-worker storage=ephemeral:NoSchedule
# k label node k8s-worker feature=aiml
# kubectl get nodes -o json | jq ".items[]|{name:.metadata.name,taints:.spec.taints}"
# n1 - ephemeral  (n1 taint storage=ephemeral:NoSchedule )  
# n2 - no storage