apiVersion: v1
kind: Pod
metadata:
  name: payroll
spec:
  restartPolicy: Always
  containers:
  - name: hello
    image: brainupgrade/hello
  tolerations:
    - key: "payroll/region"
      operator: "Equal"
      value: "india"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In  #In, NotIn, Exists, DoesNotExist, Gt, Lt  
            values:
            - ap-south-1
# k taint node ip-172-31-92-88.ec2.internal payroll/region=india:NoExecute
# k taint node ip-172-31-92-88.ec2.internal feature=aiml:NoSchedule
