apiVersion: v1
kind: Pod
metadata:
  labels:
    app: statements
    feature: aiml
  name: aiml
spec:
  containers:
  - image: brainupgrade/hello
    name: statements
  tolerations:
    - key: "feature"
      operator: "Equal"
      value: "aiml"
      effect: "NoSchedule"

# kubectl get nodes -o json | jq ".items[]|{name:.metadata.name,taints:.spec.taints}"