apiVersion: v1
kind: Pod
metadata:
  name: tourist
spec:
  restartPolicy: Always
  containers:
  - name: web-app
    image: nginx
  tolerations:
    - key: "visa/canada"
      operator: "Equal"
      value: "tourist"
      effect: "NoExecute"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In  #In, NotIn, Exists, DoesNotExist, Gt, Lt  
            values:
            - us-east-1b
      # preferredDuringSchedulingIgnoredDuringExecution:
      # - weight: 1
      #   preference:
      #     matchExpressions:
      #     - key: kops.k8s.io/instancegroup
      #       operator: In  #NotIn,  DoesNotExist for AntiAffinity
      #       values:
      #       - spotnodes
# k taint node ip-172-31-71-117.ec2.internal visa/canada=tourist:NoExecute
# k taint node ip-172-31-78-44.ec2.internal visa/canada=tourist:NoExecute
# k taint node ip-172-31-92-88.ec2.internal visa/canada=tourist:NoExecute