apiVersion: v1
kind: Pod
metadata:
  labels:
    app: image-analytics
    feature: aiml
  name: aiml
spec:
  nodeSelector:
    eks.amazonaws.com/nodegroup: gpu-nodes
  containers:
  - image: brainupgrade/hello
    name: image-analytics
  tolerations:
    - key: "feature"
      operator: "Equal"
      value: "aiml"
      effect: "NoSchedule"

# k taint node k8s-worker feature=aiml:NoSchedule
# k label node k8s-worker feature=aiml
# kubectl get nodes -o json | jq ".items[]|{name:.metadata.name,taints:.spec.taints}"